dist: trusty
sudo: false

language: cpp

os: linux
compiler: gcc-4.9
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'george-edison55-cmake-3.x']
    packages: ['g++-4.9', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip']
install: export CXX="g++-4.9" CC="gcc-4.9"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make VERBOSE=1
  - cd ..
